{
 "title": "CMM Stats",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "average",
    "label": "Average [seconds]",
    "query": "300, 600, 900, 1200, 1800, 3600, 43200, 86400, 604800"
   }
  ]
 },
 "panels": [
  {
   "title": "Amount of containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "aggregator": "avg", "metric": "container.running_count", "period": "$average" }
   ]
  },
  {
   "title": "MEM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "mem.used_perc",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Overlay space used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "aggregator": "avg",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" },
      { "key": "device", "value": "overlay" }
     ],
     "metric": "fs.usage_perc",
     "period": "$average"
    }
   ]
  },
  { "title": "CMM Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Container utilization CPU (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@image",
     "dimensions": [
      { "key": "image", "value": "$all" }
     ],
     "metric": "container.cpu.utilization_perc",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Container utilization MEM (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@image",
     "dimensions": [
      { "key": "image", "value": "$all" }
     ],
     "metric": "container.mem.used_perc",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Container io writes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@image",
     "dimensions": [
      { "key": "image", "value": "$all" },
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "container.io.write_bytes_sec",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Container io reads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@image",
     "dimensions": [
      { "key": "image", "value": "$all" },
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "container.io.read_bytes_sec",
     "period": "$average"
    }
   ]
  },
  { "title": "CMM Host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "CMM-Server",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "cpu.total_time_sec",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "CMM-Server",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "mem.used_bytes",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Overlay Disk Space Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "CMM-Server @device",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" },
      { "key": "device", "value": "overlay" }
     ],
     "metric": "fs.usage_perc",
     "period": "$average"
    }
   ]
  },
  {
   "title": "Network Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "CMM-Server out",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "net.out_bytes_sec",
     "period": "$average"
    },
    {
     "aggregator": "avg",
     "alias": "CMM-Server in",
     "dimensions": [
      { "key": "hostname", "value": "docker-host" }
     ],
     "metric": "net.in_bytes_sec",
     "period": "$average"
    }
   ]
  }
 ]
}