{
 "title": "OpenStack Services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "OpenStack Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "compute (Nova)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "none",
     "column": "value",
     "dimensions": [
      { "key": "service", "value": "compute" }
     ],
     "metric": "http_status"
    }
   ]
  },
  {
   "title": "networking (Neutron)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "none",
     "column": "value",
     "dimensions": [
      { "key": "service", "value": "networking" }
     ],
     "metric": "http_status"
    }
   ]
  },
  {
   "title": "image-service (Glance)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "none",
     "column": "value",
     "dimensions": [
      { "key": "service", "value": "image-service" }
     ],
     "metric": "http_status"
    }
   ]
  },
  {
   "title": "block-storage (Cinder)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "none",
     "column": "value",
     "dimensions": [
      { "key": "service", "value": "block-storage" }
     ],
     "metric": "http_status"
    }
   ]
  },
  {
   "title": "object-storage (Swift)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "none",
     "column": "value",
     "dimensions": [
      { "key": "service", "value": "object-storage" }
     ],
     "metric": "http_status"
    }
   ]
  },
  {
   "title": "identity-service (Keystone)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregator": "none",
     "column": "value",
     "dimensions": [
      { "key": "service", "value": "identity-service" }
     ],
     "metric": "http_status",
     "period": "300"
    }
   ]
  },
  { "title": "System Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "cpu.percent (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "cpu.percent",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "cpu.wait_perc (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "cpu.wait_perc",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "cpu.system_perc (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "cpu.system_perc",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "cpu.user_perc (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "cpu.user_perc",
     "period": "300"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "MB" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "mem.total_mb (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "mem.total_mb",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "mem.used_real_mb (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "mem.used_real_mb",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "mem.used_cache (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "mem.used_cache",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "mem.free_mb (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "mem.free_mb",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "mem.swap_total_mb (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "mem.swap_total_mb",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "mem.swap_used_mb (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "mem.swap_used_mb",
     "period": "300"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "disk.space_used_perc (@hostname @mount_point)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "mount_point", "value": "/" }
     ],
     "metric": "disk.space_used_perc",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "disk.space_used_perc (@hostname @mount_point)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "mount_point", "value": "/boot" }
     ],
     "metric": "disk.space_used_perc",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "disk.space_used_perc (@hostname @mount_point)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "mount_point", "value": "/home" }
     ],
     "metric": "disk.space_used_perc",
     "period": "300"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "load.avg_1_min (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "load.avg_1_min",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "load.avg_5_min (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "load.avg_5_min",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "load.avg_15_min (@hostname)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" }
     ],
     "metric": "load.avg_15_min",
     "period": "300"
    }
   ]
  },
  { "title": "Network monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "net.in_bytes_sec (@hostname @device)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "device", "value": "$all" }
     ],
     "metric": "net.in_bytes_sec",
     "period": "300"
    },
    {
     "aggregator": "avg",
     "alias": "net.out_bytes_sec (@hostname @device)",
     "column": "value",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "device", "value": "$all" }
     ],
     "metric": "net.out_bytes_sec",
     "period": "300"
    }
   ]
  }
 ]
}