{
 "title": "OpenStack VMs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "cpu.utilization_perc",
     "period": "300"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "mem.used_gb",
     "period": "300"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "mem.free_gb",
     "period": "300"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "mem.total_gb",
     "period": "300"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "net.in_bytes_sec",
     "period": "300"
    }
   ]
  },
  {
   "title": "Network received total bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "net.in_bytes",
     "period": "300"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "net.out_bytes_sec",
     "period": "300"
    }
   ]
  },
  {
   "title": "Network transmitted total bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "net.out_bytes",
     "period": "300"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk I/O write bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "io.write_bytes_sec",
     "period": "300"
    }
   ]
  },
  {
   "title": "Disk I/O read bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "io.read_bytes_sec",
     "period": "300"
    }
   ]
  }
 ]
}