{
 "title": "OpenStack Hypervisor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "VM Aggregate Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total of memory allocated to all VMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "aggregator": "none", "alias": "@hostname", "metric": "nova.vm.mem.total_allocated_mb", "period": "300" }
   ]
  },
  {
   "title": "Total of disk space allocated to all VMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "none",
     "alias": "@hostname",
     "metric": "nova.vm.disk.total_allocated_gb",
     "period": "300"
    }
   ]
  },
  {
   "title": "Total CPUs allocated across all VMs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "aggregator": "none", "alias": "@hostname", "metric": "nova.vm.cpu.total_allocated", "period": "300" }
   ]
  },
  { "title": "CPU and Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.cpu.utilization_perc",
     "period": "300"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.mem.used_gb",
     "period": "300"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.mem.free_gb",
     "period": "300"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.mem.total_gb",
     "period": "300"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Network received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.net.in_bytes_sec",
     "period": "300"
    }
   ]
  },
  {
   "title": "Network received total bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.net.in_bytes",
     "period": "300"
    }
   ]
  },
  {
   "title": "Network transmitted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.net.out_bytes_sec",
     "period": "300"
    }
   ]
  },
  {
   "title": "Network transmitted total bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.net.out_bytes",
     "period": "300"
    }
   ]
  },
  { "title": "Disk I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk I/O write bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.io.write_bytes_sec",
     "period": "300"
    }
   ]
  },
  {
   "title": "Disk I/O read bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "@hostname",
     "dimensions": [
      { "key": "hostname", "value": "$all" },
      { "key": "component", "value": "vm" }
     ],
     "metric": "vm.io.read_bytes_sec",
     "period": "300"
    }
   ]
  }
 ]
}