repository: monasca/log-api
variants:
  - tag: master
    aliases:
      - :master-{date}-{time}
    args:
      LOG_API_BRANCH: master
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
      CONSTRAINTS_BRANCH: master

  - tag: 2.2.3
    aliases:
      - :latest
      - :2.2
      - :2
    args:
      LOG_API_BRANCH: 2.2.1
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
      CONSTRAINTS_BRANCH: master
  - tag: 2.1.0
    aliases:
      - :2.1
    args:
      LOG_API_BRANCH: 2.1.0
      CONSTRAINTS_BRANCH: master
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
  - tag: 2.0.0
    aliases:
      - :2.0
    args:
      LOG_API_BRANCH: 2.0.0
      CONSTRAINTS_BRANCH: master
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207

  - tag: ocata
    aliases:
      - :ocata-{date}-{time}
    args:
      LOG_API_BRANCH: stable/ocata
      CONSTRAINTS_BRANCH: stable/ocata
      PYTHON_VERSION: '2'
      TIMESTAMP_SLUG: 20170809-155207
