version: '2'
services:

  log-metrics:
    hostname: docker-host
    image: fest/log-metrics:${MON_LOG_METRICS_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-metrics"
    depends_on:
      - kafka
      - zookeeper
      - log-transformer

  log-persister:
    hostname: docker-host
    image: fest/log-persister:${MON_LOG_PERSISTER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-persister"
    depends_on:
      - kafka
      - zookeeper
      - elasticsearch
      - log-transformer

  log-transformer:
    hostname: docker-host
    image: fest/log-transformer:${MON_LOG_TRANSFORMER_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=monasca-log-transformer"
    depends_on:
      - kafka
      - zookeeper
      - log-api

  elasticsearch:
    hostname: docker-host
    image: fest/elasticsearch:${MON_ELASTICSEARCH_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=elasticsearch"
    volumes:
      - ${MON_DOCKER_VOL_ROOT}/elasticsearch/data:/usr/share/elasticsearch/data
      - ${MON_BACKUP_DIR}/elasticsearch_backup:/elasticsearch_backup

  elasticsearch-init:
    hostname: docker-host
    image: fest/elasticsearch-init:${MON_ELASTICSEARCH_INIT_VERSION}
    environment:
      LOGSTASH_FIELDS: "service=elasticsearch-init"
    depends_on:
      - elasticsearch

  elasticsearch-curator:
    hostname: docker-host
    image: fest/elasticsearch-curator:${MON_ELASTICSEARCH_CURATOR_VERSION}
    environment:
      CURATOR_EXCLUDED_INDEX_NAME: .kibana
      CURATOR_DELETE_BY_AGE: ${MON_ELASTICSEARCH_DATA_RETENTION_DAYS}
      LOGSTASH_FIELDS: "service=elasticsearch-curator"
    depends_on:
      - elasticsearch

  kafka-log-init:
    hostname: docker-host
    image: fest/kafka-init:${MON_KAFKA_INIT_VERSION}
    environment:
      KAFKA_TOPIC_CONFIG: segment.ms=900000 # 15m
      KAFKA_CREATE_TOPICS: "\
        log:4:1,\
        log-transformed:4:1"
      LOGSTASH_FIELDS: "service=kafka-log-init"
    depends_on:
      - kafka

  kibana:
    hostname: docker-host
    image: fest/kibana:${MON_KIBANA_VERSION}
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_PINGTIMEOUT: 1000
      LOGSTASH_FIELDS: "service=kibana"
    depends_on:
      - elasticsearch
      - keystone
    ports:
      - 5601:5601

  log-api:
    hostname: docker-host
    image: fest/log-api:${MON_LOG_API_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=monasca-log-api"
    depends_on:
      - keystone
      - zookeeper
      - kafka
      - memcached
    ports:
      - "5607:5607"

  log-agent:
    hostname: docker-host
    image: fest/log-agent:${MON_LOG_AGENT_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=monasca-log-agent"
    depends_on:
      - log-api
      - keystone

  logspout:
    hostname: docker-host
    image: fest/logspout:${MON_LOGSPOUT_VERSION}
    environment:
      LOGSPOUT: ignore
      LOGSTASH_FIELDS: "service=logspout"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
        - log-agent
