---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: monitoring
  name: kafka.prometheus
data:
  kafka-config.yml: |
    ---
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:7203/jmxrmi
    
    lowercaseOutputName: true
    rules:
    - pattern: '"kafka.controller"<type="(KafkaController)", name="(OfflinePartitionsCount|ActiveControllerCount)"><>(Value)'
      name: kafka_controller_$1_$2
    - pattern: '"kafka.server"<type="(ReplicaManager)", name="(UnderReplicatedPartitions)"><>(Value)'
      name: kafka_server_$1_$2
    # This metric doesn't appear to be available in 0.8.1.1
    #- pattern: '"kafka.server"<type="(KafkaServer)", name="(BrokerState)"><>(Value)'
    #  name: kafka_server_$2
    - pattern: '"kafka.server"<type="(BrokerTopicMetrics)", name="AllTopics(Bytes|Messages)(In|Out)PerSec"><>(Count)'
      name: kafka_server_$1_$2_$3_total
      labels:
        topic: all_topics
    - pattern: '"kafka.server"<type="(BrokerTopicMetrics)", name="(.+)-(Bytes|Messages)(In|Out)PerSec"><>(Count)'
      name: kafka_server_$1_$3_$4_total
      labels:
        topic: $2
    - pattern: '"kafka.network"<type="(RequestMetrics)", name="Fetch-(Consumer|Follower)-TotalTimeMs"><>(Count)'
      name: kafka_network_$1_fetch_$2_total_ms
    - pattern: '"kafka.network"<type="(RequestMetrics)", name="Produce-(Local|Remote|Total|ResponseQueue)TimeMs"><>(Count)'
      name: kafka_network_$1_produce_$2_ms
    # These metric doesn't appear to be available in 0.8.1.1
    #- pattern: '"kafka.server"<type="(KafkaRequestHandlerPool)", name="(RequestHandlerAvgIdlePercent)"><>(Count)'
    #  name: kafka_server_$1_$2
    #- pattern: "kafka.network"<type="(SocketServer)", name="(NetworkProcessorAvgIdlePercent)"><>(Value)'
    #  name: kafa_network_$1_$2
    - pattern: '"kafka.controller"<type="(ControllerStats)", name="(UncleanLeaderElectionsPerSec|LeaderElectionRateAndTimeMs)"><>(Count)'
      name: kafka_controller_$1_$2
    - pattern: '"kafka.server"<type="(ReplicaFetcherManager)", name="(Replica)-(MaxLag)"><>(Value)'
      name: kafka_server_$1_$3
      labels:
        topic: $2
    - pattern: '"kafka.server"<type="(ReplicaManager)", name="Isr(Expands|Shrinks)PerSec"><>(Count)'
      name: kafka_server_$1_isr_$2_per_sec

