- name: Minimize keystone footprint
  hosts: localhost
  sudo: yes
  tasks:
    - lineinfile: dest=/etc/keystone/keystone.conf regexp="^#public_workers" line="public_workers = 2"
    - lineinfile: dest=/etc/keystone/keystone.conf regexp="^#admin_workers" line="admin_workers = 2"

- name: Installs zookeeper, startup zookeeper for use later
  hosts: localhost
  sudo: yes
  roles:
    - {role: zookeeper, tags: [zookeeper]}
  tasks:
    - shell: 'keystone-all --config-file /etc/keystone/keystone.conf &'

- name: Installs mysql
  hosts: localhost
  sudo: yes
  vars:
    mysql_root_password: password
  roles:
    - {role: percona, tags: [mysql, percona]}

- name: Set up mysql schema
  hosts: localhost
  sudo: yes
  vars:
    mysql_admin: root
    mysql_admin_password: password
    kafka_topics_enabled: false
    influxdb_schema_enabled: false
    mysql_schema_enabled: true
    winchester_schema_enabled: false
    mon_mysql_users:
    - username: notification
      password: password
    - username: monapi
      password: password
    - username: thresh
      password: password
  roles:
    - {role: monasca-schema, tags: [schema]}

- name: Installs kafka
  hosts: localhost
  sudo: yes
  vars:
    kafka_heap_opts: "-Xmx256m"
    zookeeper_hosts: localhost:2181
    verify: False
  roles:
    - {role: kafka, tags: [kafka]}

- name: Installs influxdb
  hosts: localhost
  sudo: yes
  vars:
    mon_influxdb_users:
    - username: mon_api
      password: password
    - username: mon_persister
      password: password
    influxdb_url: http://localhost:8086
    kafka_topics_enabled: false
    kafka_events_partitions: 4
    kafka_metrics_partitions: 4
    kafka_replicas: 1
    mysql_schema_enabled: false
    winchester_schema_enabled: false
  roles:
    - {role: influxdb, tags: [influxdb]}
    - {role: monasca-schema, tags: [schema]}

- include: keystone.yml monasca_api_url=http://localhost:8080/v2.0

- name: Install Monasca persister
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: localhost:9092
    influxdb_host: localhost
    influxdb_url: http://localhost:8086
    influxdb_user: mon_persister
    influxdb_password: password
    influxdb_version: 0.9.0-rc22
    zookeeper_hosts: localhost:2181
  roles:
    - {role: monasca-persister, tags: [persister]}

- name: Install Monasca api
  hosts: localhost
  sudo: yes
  vars:
    api_region: mini-mon
    influxdb_url: http://localhost:8086
    influxdb_user: mon_api
    influxdb_password: password
    influxdb_version: 0.9.0-rc22
    kafka_hosts: localhost:9092
    keystone_host: localhost
    keystone_auth_method: token
    keystone_admin: admin
    keystone_admin_token: ADMIN
    keystone_admin_password: admin
    mysql_host: localhost
    mysql_user: monapi
    mysql_password: password
    zookeeper_hosts: localhost:2181
    verify: False
  roles:
    - {role: monasca-api, tags: [api]}

- name: Install Monasca notification
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: localhost:9092
    mysql_host: localhost
    mysql_user: notification
    mysql_password: password
    smtp_host: localhost
    zookeeper_hosts: localhost:2181
  roles:
    - {role: monasca-notification, tags: [notification]}
  tasks:
    - name: Install postfix, needed by notification engine
      apt: name=postfix state=present

- name: Install monasca-agent
  hosts: localhost
  sudo: yes
  vars:
    keystone_url: http://localhost:35357/v3
    monasca_api_url: http://localhost:8080/v2.0
    monasca_agent_check_frequency: 5
    monasca_agent_user: monasca-agent
    monasca_agent_password: password
    monasca_agent_project: mini-mon
    monasca_agent_service: monitoring
  roles:
    - {role: monasca-agent, tags: [agent]}
  post_tasks:
    - shell: 'echo "log_to_syslog: no" >> /etc/monasca/agent/agent.conf'

- name: Install Storm
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: localhost:9092
    mysql_host: localhost
    mysql_user: thresh
    mysql_password: password
    nimbus_host: localhost
    storm_nimbus_enabled: true
    storm_nimbus_extra_config:
        nimbus.childopts: "-Xmx512m"
    storm_supervisor_enabled: true
    storm_supervisor_extra_config:
        supervisor.childopts: "-Xmx512m"
    storm_worker_extra_config:
        worker.childopts: "-Xmx512m -XX:+UseConcMarkSweepGC -Dcom.sun.management.jmxremote"
    storm_worker_ports: [6701]
    zookeeper_hosts: localhost:2181
    verify: False
  roles:
    - {role: storm, tags: [storm]}

- name: Install Monasca Thresh
  hosts: localhost
  sudo: yes
  vars:
    kafka_hosts: localhost:9092
    mysql_host: localhost
    mysql_user: thresh
    mysql_password: password
    nimbus_host: localhost
    zookeeper_hosts: localhost:2181
    verify: False
  pre_tasks:
    - shell: /opt/storm/current/bin/storm nimbus &
    - shell: /opt/storm/current/bin/storm supervisor &
    - command: sleep 60
  roles:
    - {role: monasca-thresh, tags: [thresh]}
