- name: Sets up kafka topics
  hosts: localhost
  sudo: yes
  vars:
    kafka_events_partitions: 4
    kafka_metrics_partitions: 4
    kafka_replicas: 1
    kafka_topics_enabled: true
    influxdb_schema_enabled: false
    mysql_schema_enabled: false
    winchester_schema_enabled: false
    zookeeper_hosts: localhost:2181
  roles:
    - {role: monasca-schema, tags: [schema]}

